---
output:
  html_document:
    toc: no
---
# Course Schedule

|**Section**|**Activity**|**Required reading/Notes**|**In-class Assignment**|
|---                    |---                                            |---                                |---|
|Introduction 1.1 to 1.8|Introduction to data and statistical analysis  |Kachigan p. 3 to 25, Broman and Woo (2018), Zar Ch 1.1 to 1.2       |   |
|   |Labor Day                                      |                                                                    |   |
|Introduction 2.1 to 2.28   |Frequency Distributions and Variation          |Kachigan p. 29 to 69, Zar Ch 1.3 to 1.4 and Ch 3 to 4               |   |
|Introduction 3.1 to 3.8   |Probability, Sampling, and Parameters          |Kachigan p. 73 to 159, Zar Ch 5, Zar 6.1 to 6.3                     |   |
|   |In class assignment                            |                                                                    |   |
|Introduction 4.1 to 4.21   |Hypothesis Testing and Statistical Power       |Kachigan p. 160 to 192, Trafimow et al. 2017, Benjamin et al. 2018, Zar Ch 6.4, Zar Ch 7.1 to 7.3|   |
|   |In class assignment                            |                                                                    |   |
|Introduction 5.1 to 5.11   |Correlation                                    |Kachigan p. 195 to 237, Fields et al. Ch 6, Zar Ch 17.1, Zar Ch 19.9|   |
|   |**Midterm 01 (Class 01 to 07), HW01 Due**      |                                                                    |   |
|Linear Models 1.1 to 1.23   |Review Midterm 01, Simple Linear Regression    |Kachigan p. 238 to 259, Fields et al. Ch 7, Zar Ch 17               |   |
|Linear Models 2.1 to 2.16   |Multiple Linear Regression                     |Zar Ch 20                                                           |   |
|   |In class assignment                            |Kachigan p. 259 to 271, Fields et al. Ch 7                          |   |
|   |Fall Break                                     |                                                                    |   |
|Linear Models 3.1 to 3.23   |Comparing two means                            |Fields et al. Ch 9                                                  |   |
|   |In class assignment                            |                                                                    |   |
|Linear Models 5.1 to 5.29  |One-way ANOVA                                  |Kachigan p. 272 to 282, Fields et al. Ch 10                         |   |
|   |In class assignment                            |                                                                    |   |
|   |Factorial ANOVA                                |Kachigan p. 282 to 330, Fields et al. Ch 12                         |   |
|   |**Midterm 02 (Class 09 to 16), HW02 Due**      |                                                                    |   |
|Linear Models 6.1 to 6.13   |Analysis of Categorical Data, Review Midterm 02|Kachigan p. 342 to 356, Zar Ch. 22 and 23                           |   |
|   |In class assignment                            |                                                                    |   |
|   |Non-parametric statistical methods             |Fields et al. Ch 15                                                 |   |
|   |In class assignment                            |                                                                    |   |
|   |Computer-intensive methods                     |Hesterberg (2015)                                                   |   |
|   |In class assignment                            |                                                                    |   |
|   |Non-linear curve fitting and AIC               |Burnham and Anderson (2011)                                         |   |
|   |**Midterm 03 (Class 18 to 24), HW03 Due**      |                                                                    |   |
|   |Midterm review                                 |                                                                    |   |
|   |**Final Exam**                                 |                                                                    |   |
