---
output:
  html_document:
    toc: no
---
# Robert Leaf, PhD 

# Biography: 

Dr. Robert Leaf joined the Division of Coastal Sciences in the School of Ocean Science and Engineering in 2012. His research interests lie in fishery science and computer-intensive modeling approaches for management and conservation of living marine resources. The goals of these analyses are to understand the biological and ecosystem processes that determine population dynamics and to incorporate this understanding for effective conservation and management strategies.   

He received a PhD in Fishery and Wildlife Sciences from the Virginia Polytechnic Institute and State University in 2010. There he studied how life history characteristics of individuals in harvested populations are altered under size-selective exploitation. As a post-doctoral researcher at NOAA Fisheries, Dr. Leaf examined how phytoplankton bloom phenology determines recruitment patterns in the Haddock stock. His current work involves assessment of fisheries and populations, primarily in the Gulf of Mexico but also in the northeastern and mid-Atlantic regions of the United States.

# Current Projects: 
 
“Understanding the utility of archived tag-recapture data for evaluation of movement and mortality estimation”
 
This project is focused on performing exploratory analysis to understand the feasibility of a comprehensive reanalysis of a tag and recapture data set of Gulf Menhaden, performed in the 1970’s to 1990’s. The primary focus of the work is to catalog, organize, and summarize the paper records held by NOAA at Beaufort. A primary focus will be to evaluate the paper data for completeness for the Gulf of Mexico Menhaden Stock.
 
“Evaluation of Discard Patterns in Mid-Atlantic Groundfish and Pelagic Fisheries”
 
This project has two primary aspects. The first is to perform statistical predictive analysis to understand what constitutes a directed trip in selected groundfish fisheries. The work will primarily employ a machine learning algorithm called “random forest” which is a classification approach. In the analysis we focus on identifying the gears, fleet characteristics, temporal and spatial characteristics, and sectors that lead to high discards. The second approach used in the study will be a qualitative analysis. We will create a dashboard will provide graphical summary (in space and time) to understand the discard patterns with respect to gear types, fleet characteristics, temporal and spatial characteristics.
 
“Evaluating the impact of plus group definition on the Gulf and Atlantic Menhaden stock assessments”
 
This project examines the impact of the plus group definition on population estimates generated by the Gulf and Atlantic Menhaden stock assessment models. The approach is to develop a a stochastic data-generating model to create realistic simulated catch and survey data with varying proportions of older fish in the population and fishery catch. Using these simulated data, the stock assessment model BAM, using configurations that differ in plus groups definition (e.g., Gulf: ages 3+,4+,5+; Atlantic: ages 3+,4+…8+) will be evaluated. Accuracy and precision of model estimates of fishery selectivity and age-specific abundance and fishing mortality will be compared among plus groups and across all population levels for each species. Our results will be communicated in person to the GSMFC Menhaden Advisory Committee and the ASMFC Atlantic Menhaden Technical Committee prior to the next benchmark assessment workshop for each species.
 
“Assessment and monitoring of Mississippi's fishery resources”

The goals of the proposed work are to identify stocks in need of assessment (termed "stock under consideration"), in collaboration with the Commission and agency representatives for the MDMR and to evaluate the scientific data available and identify data gaps in the understanding of relative abundance and life-history information needed to complete a robust and defensible (peer reviewed) stock assessment. Based on the availability of data and the needs of the Mississippi Department of Marine Resources, we will conduct a state-of-the-art assessment for the stock(s) under consideration and present the results to the Commission. Thus far this work has resulted in 5 peer reviewed stock assessment products used for managing our state’s coastal fisheries. 
